# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend image
      run: |
        docker build -t your-dockerhub-username/backend:latest ./backend
        docker push your-dockerhub-username/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t your-dockerhub-username/frontend:latest ./frontend
        docker push your-dockerhub-username/frontend:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          ./deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
